var Plexus = module.plexus.Plexus;
var Backbone = module.plexus.Backbone;
var express = module.plexus.express;
var middleware = module.plexus.middleware;
var controllers = require('..').controllers;
var models = require('..').models;
var routers = require('..').routers;
var servers = require('..').servers;
var views = require('..').views;
var templates = require('..').templates;
var commands = require('..').commands;
var command;