var Bones = module.bones.Bones;
var Backbone = module.bones.Backbone;
var express = module.bones.express;
var middleware = module.bones.middleware;
var controllers = require('..').controllers;
var models = require('..').models;
var routers = require('..').routers;
var servers = require('..').servers;
var views = require('..').views;
var templates = require('..').templates;
var commands = require('..').commands;
var command;